### ISSUE TITLE
how to Customizing the session ui

### ISSUE THREAD

**Issue by HuYuee** [opentok/opentok-react#54] opened 2019-02-12 06:10 UTC
how to Customizing the session ui ? can you give me some example about custom ui ? Thanks

**Comment by msach22** [comment] 2019-02-13 16:11
@HuYuee This seems to be a duplicate of the following:
https://github.com/opentok/opentok-react/issues/40

I'm going to go ahead and close the issue, but if your issue still persist, please feel free to reopen.

**Closed by msach22** 2019-02-13 16:11 UTC

**Comment by HuYuee** [comment] 2019-02-14 07:50
Thanks，i solved it to watch the example code of opentok-react. i provided some code snippets the following:
```
return apiKey && sessionId && token ? (
      <OTSession
        apiKey={apiKey}
        sessionId={sessionId}
        token={token}
        eventHandlers={this.sessionEvents}
        onError={this.onError}
      >
        {connected ? (
          <div className="phoneContent">
            <h5>{name}</h5>
            <p>{number}</p>
            <span>
              <Icon
                type="phone"
                theme="twoTone"
                twoToneColor="#D64C4E"
                onClick={this.handUp}
              />
            </span>
            <Prompt message="Are you sure to leave? The phone will be hung up when leave." />
          </div>
        ) : (
          ""
        )}

        <div style={{ display: "none" }}>
          <OTPublisher
            properties={{
              subscribeToAudio: this.state.audio,
              subscribeToVideo: this.state.video
            }}
            eventHandlers={this.publisherEventHandlers}
          />
          <OTStreams>
            <OTSubscriber eventHandlers={this.subscriberEventHandlers} />
          </OTStreams>
        </div>
      </OTSession>
    ) : (
      ""
    );
  }
```
