### ISSUE TITLE
Cannot screenshare on Mac OS X

### ISSUE THREAD

**Issue by B-0-B-B-Y** [opentok/opentok-react#152] opened 2020-09-10 15:14 UTC
**Describe the problem?**

Application built using latest version of @opentok/react and react 16.13.1 with functional components.

Code sample of setup for screensharing:

Video source set as state, defaults to `camera`:

```
const [videoSource, setVideoSource] = useState('camera');
```

OTSession setup is as follows:

```
        <OTSession
          apiKey={apiKey}
          sessionId={sessionId}
          token={token}
          onError={onSessionError}
          eventHandlers={sessionEventHandlers.current}
          ref={session}
        >
          <OTStreams>
            <div className='call-screen__advisor-feed'>
              <OTSubscriber
                properties={{ width: '100%', height: '100%' }}
                onSubscribe={onSubscribe}
                onError={onSubscribeError}
                eventHandlers={subscriberEventHandlers}
              />
            </div>
          </OTStreams>
          <div className='call-screen__customer-feed'>
            <OTPublisher
              properties={{
                publishAudio,
                publishVideo,
                videoSource,
                width: '100%',
                height: '100%',
              }}
              onPublish={onPublish}
              onError={onPublishError}
              eventHandlers={publisherEventHandlers}
            />
          </div>
        </OTSession>
```
When videoSource is provided in the properties object, attempting to change the videoSource with a button click event to `'screen'` from '`camera'` results in the call crashing with OT constraints not met: 1500 error code. 

This exact same setup works fine on Linux/Windows machines.

https is enabled and in use, screen sharing and screen recording permissions are granted in system preferences, chrome has access to microhpone, camera and screen. On the dedicated Mac test machine, Goggle hangouts can share screen without issue, so all permissions are definitely granted for screen sharing. This has been tested across all three major browsers on Mac, namely the latest versions of Chrome, Safari and Firefox, with the same exact issue across the board.

It seems to me some kind of race condition is happening, because the browser does not display the url bar pop up which normally appears asking you to grant permissions to this tab to record audio/video. When switching to screenshare, the same tab appears asking which screen to share when using Linux and Windows, but that pop up doesn't show on Mac when attempting to switch to screen as the video source.

**Expected outcome**

Screenshare works on Mac just like it does on Linux and Windows.

**Comment by enricop89** [comment] 2020-09-17 09:24
Hi @B-0-B-B-Y , I ran a few tests and I believe the problem is how you set the videoSource property on the `Publisher` component. 

Let me explain: the videoSource value on the React state (your code) can have two values: camera or screen. 
Also, the videoSource on the `OTPublisher` can have different values ([Documentation](https://tokbox.com/developer/sdks/js/reference/OT.html#initPublisher)), such as String, Boolean and MediaStreamTrack. Even though 'screen' is a valid value, 'camera' is not. If you set camera as videoSource value, the browser will try to get a camera device with ID `camera` (open a new tab on Chrome and type chrome://webrtc-internals, under Get User Media requests), which won't exist on your device.

A quick fix is the following: 

```
<OTPublisher
              properties={{
                publishAudio,
                publishVideo,
                videoSource: this.state.videoSource === 'screen' ? 'screen' : undefined,
                width: '100%',
                height: '100%',
              }}
              onPublish={onPublish}
              onError={onPublishError}
              eventHandlers={publisherEventHandlers}
/>
```

Let me know if it helps.

**Comment by enricop89** [comment] 2020-10-06 07:52
@B-0-B-B-Y I'll close the issue. Please re-open if needed

**Closed by enricop89** 2020-10-06 07:52 UTC
