### ISSUE TITLE
Unable to hear voice  In iPhones

### ISSUE THREAD

**Issue by KunalBurangi** [opentok/opentok-react#53] opened 2019-02-05 05:43 UTC
when in Video Call between any IOS devices user is unable to hear voice of other end is there any work around?

**Comment by msach22** [comment] 2020-03-20 17:12
@KunalBurangi I'm closing this issue because I'm not able to reproduce this. If you're seeing this, please file a ticket with support or open another ticket.

**Closed by msach22** 2020-03-20 17:12 UTC
